name: Publish

on:
  push:
    branches:
    - master

jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Checkout repo
      uses: actions/checkout@v1.0.0
    - name: Git Identity
      run: |
        git config --global user.name '@blueboxes'
        git config --global user.email 'blueboxes@users.noreply.github.com'
        git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
    - name: Pulling
      run: git pull
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Authenticate with Registry
      run: |
          yarn logout
          echo "@blueboxes/gatsby-theme-novela:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
      env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish with Lerna
      run: yarn lerna publish --yes --message 'chore(release)'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
